language: generic
dist: trusty
sudo: false

addons:
  apt:
    packages:
      - cmake

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5

    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.8
          packages:
            - clang-3.8

before_script:
  - mkdir _build
  - cd _build

script: 
  - cmake .. && make && ./avakar_bigint_test
